# Build and run the PlaySpotApi project using Docker
# Use the official .NET SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /App

# Copy the project files to the container
COPY . ./
RUN dotnet restore PlaySpotApi.sln
RUN dotnet publish PlaySpotApi.sln -c Release -o out

# Use the official .NET runtime image to run the application
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /App
COPY --from=build /App/out .
EXPOSE 8080
ENTRYPOINT [ "dotnet", "PlaySpotApi.dll" ]
