# Build and run the PlaySpotApi project using Docker
# Use the official .NET SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /App

# Install the .NET EF Core tool
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

# Copy the project files to the container
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

# Use the official .NET runtime image to run the application
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /App
COPY --from=build /App/out .

ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80

ENTRYPOINT [ "dotnet", "PlaySpotApi.dll" ]
